((magit-blame
  ("-w"))
 (magit-commit nil)
 (magit-diff
  ("--no-ext-diff" "--stat")
  (("--" "client/game/script/gcore/spells/auto_chess_qingwaciqi_spl2.py")
   "--no-ext-diff" "--stat")
  (("--" "client/game/script/gcore/notifys/buff_notify.py")
   "--no-ext-diff" "--stat")
  (("--" "client/game/script/gcore/components/buff_comp.py"))
  (("--" "client/game/script/SunshineClient/SunshineSDK/LocalRpc.py"))
  (("--" "client/game/script/new_gm_main.py")))
 (magit-dispatch nil)
 (magit-log
  (("--" "client/game/script/gcore/bases/notify_manager.py"))
  (("--" "client/game/script/game_ui/spell_area_nodes/components/cast_ring_comp.py"))
  (("--" "client/game/script/editor_core/systems/missile_system.py"))
  (("--" "client/game/script/gcore/spells/eqp_tianyu.py"))
  (("--" "client/game/script/game_ui/panel_nodes/minimap_components/minimap_comp_ui_btn.py"))
  (("--" "client/game/script/new_gm_main.py"))
  ("-n256" "--graph" "--decorate" "--patch"))
 (magit-stash nil)
 (magit:-- "client/game/script/gcore/spells/auto_chess_qingwaciqi_spl2.py" "" "client/game/script/gcore/notifys/buff_notify.py")
 (magit:--author "luh"))
